# application-dev.properties
# Activar con: mvn spring-boot:run -Dspring-boot.run.profiles=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/nexusdb_dev
spring.datasource.username=nexus
spring.datasource.password=nexus_password_2026

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=nexus-dev-secret-key-esta-clave-solo-para-desarrollo
jwt.expiration=86400000

logging.level.com.todoeconometria.nexus=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
